spring:
  application:
    name: weather-app
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true